---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  s3-bucket:
  s3_access_key_id:
  s3_secret_access_key:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:
  IAAS:

inputs:
  - name: s3-ert-metadata
  - name: s3-ert-binary
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/upload-product-and-stemcell/task.sh
